queue_documents_for_indexing:
  cron: "0 0 * * *"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1hr
  class: AccountQueuer
  queue: account_queue
  args: 
  description: "Loads accounts to be processed every day"